# This is action file where your all repetative jobs and steps will be defined here.
# It will be use in your workflow yml file.

name: 'Using Output Get & Cache Dependencies'
description: "Combine steps of npm install and cache it."
# use inputs: key for caching by default: true
inputs:
  caching:
    description: 'Wheather caching requires of dependencies or not'
    required: false
    default: 'true' # If default: 'false' -- It will not performs "Cache Dependencies" Steps.

    # But for some reasons, if you dont want to install dependencies from caching in lint job.
    # with:
    #   caching: 'false' 
    # in that workflow.yml files. But, it will reinstall npm and dependencies.
    # Go to deploy.yml > jon: lint > with: caching: 'false'
outputs:
  used-cache:
    description: "Whether the cache was used."
    # value: ${{ steps.cache.outputs.cache }}
    value: ${{ steps.cache.outputs.cache-hit }}

runs:
  using: composite
  steps: 
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v3
      if: inputs.caching == 'true'
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      run: | 
        npm ci
        echo "::set-output name=cache::'${{ inputs.caching }}'"
      if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
      shell: bash